project_id = "bkznuajqtfjezzeqqamz"

[functions.aria-chat]
verify_jwt = false

[functions.send-agent-invite]
verify_jwt = false

[functions.analyse-agent-files]
verify_jwt = false

[functions.resend-agent-invite]
verify_jwt = false

[functions.classify-intent]
verify_jwt = false

[functions.admin-set-user-role]
verify_jwt = false
