// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkznuajqtfjezzeqqamz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrem51YWpxdGZqZXp6ZXFxYW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTM2MjIsImV4cCI6MjA4NzA2OTYyMn0.qrbRbsnzw2i-iJdaoSVQBglrHbCI4oMhVcMjeimRlbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});